### ISSUE TITLE
Skip some relation

### ISSUE THREAD

**Issue by ReshuAgarwal** [knowitall/openie#11]
Hi,

OpenIE 4.0's results are very good then others, but i noticed a bug in it i.e it is skipping some phrase as given below:

Sentence:
World leaders should halt these visits and link any deal with Iran to its human rights record.  ( to its human rights record)

SVO:
List(0.93 (World leaders; should halt; these visits),

 0.94 (World leaders; link; any deal with Iran))

**Comment by bhadramani** [comment]
Mostly OpenIE(s) are not based on deterministic methods, good chances it skips few more, so keep informing , these patterns may be part of future versions. Thanks...

**Comment by bhadramani** [comment]
Since no followup , closing.
