### ISSUE TITLE
How to train model

### ISSUE THREAD

**Issue by guoyangrui** [knowitall/openie#15]
Hello, maybe here isn't the best place to ask questions but the software has too few tutorials available. I have two questions. First, how should I perform the triplet search (who/what - relation who/what) featured in OpenIE home page using the downloaded software? Second, how can I add my own data to its knowledge base? Thank you

**Comment by bhadramani** [comment]
You can create your own knowledge base, buy pushing triples in database and indexing it. You may like to look at license terms before using OpenIE 4.x for extracting triples.
