### ISSUE TITLE
Question about the results obtained

### ISSUE THREAD

**Issue by lore10** [knowitall/openie#16]
Thank you for share your IE tool!!

My name is Lorena and please, I would like to know what the numerical quantities presented for each result mean. (0,52 and 0,93 next)

Here an example:
If he wins five key states, Romney will be elected President.
[info] If he wins five key states, Romney will be elected President.
[info] 0,52 (he; wins; five key states)
[info] 0,93 (Romney; will be elected; President)

Thanks!!

**Comment by bhadramani** [comment]
This indicates Confidence level for extraction.

**Comment by lore10** [comment]
Thanks!! King regards.
Lorena
