### ISSUE TITLE
Failing to create stand-alone jar.

### ISSUE THREAD

**Issue by h1395010** [knowitall/openie#17]
I've run the commands described in the README document, i.e. the variations of:
'sbt clean compile assembly'
However my machine is just stuck on the following screen:
![cap](https://cloud.githubusercontent.com/assets/9053984/5812409/091f6dde-a0a5-11e4-830d-b077ca1767bc.png)
Is there something I can do to compel this jar file into existence?

What I actually want to do is to input my own data to OpenIE and specify the output destination, is that possible if one runs the program with the command
sbt 'run-main edu.knowitall.openie.OpenIECli'

It seems like the specifications for particular data input parameters are set up to work with the .jar file, at least according to the README doc.

**Comment by bhadramani** [comment]
Then should use java option -J-Xmx2700M or -J-Xmx4G as mention in Readme.

**Comment by h1395010** [comment]
I attempted that but the result was the same

**Comment by bhadramani** [comment]
you should have 4-8GB memory along with jdk7.

**Comment by h1395010** [comment]
maybe it's because I have jdk8?

**Comment by bhadramani** [comment]
hope it is solved...

**Comment by skprasadu** [comment]
Looks like it is only windows specific issue. This can be built both by Java 7 and Java 8, but the way to build it is,

set JAVA_OPTS=-Xmx4g && sbt clean compile assemly

It will take about 15min and will be built.
