### ISSUE TITLE
It seems the output needs some clarification

### ISSUE THREAD

**Issue by matanster** [knowitall/openie#20]
It appears that an explanation of the output should be part of the readme (the project's single test provides little insight here). Whereas it is feasible to understand that OpenIE would output triplets, or triplets through an abbreviated n-ary notation, a simple example as one provided, also includes a context element of unspecified semantics. 

```
John ran down the road to fetch a pail of water.
[info] John ran down the road to fetch a pail of water.
[info] 0.86 (John; ran; down the road; to fetch a pail of water)
[info] 0.82 Context(John ran,List([0, 8))):(John; ran down the road to fetch; a pail of water)
```

Whether this follows in the output format of Ollie or Reverb or not, the output format should be described by text, code examples or tests, or alternatively a link to any article describing it should better imo be  provided.

**Comment by bhadramani** [comment]
You may use --binary  which gives the binary(triples) output .
