### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by askmyhat** [knowitall/openie#25]
Nothing happens after tests.

```
...
[info] - should instantiate and extract correctly
[info] Run completed in 2 minutes, 53 seconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

The compilation was runned with `sbt clean compile assembly`

**Comment by KevinBassaDevelopment** [comment]
I have exactly the same problem.
Steps I have done:
1) Got project from https://github.com/knowitall/openie.git
2) Downloaded all dependencies with 'sbt compile'
3) Tried to create a standalone jar with 'sbt clean compile assembly'
--> Runs until:
[info] - should instantiate and extract correctly
[info] Run completed in 2 minutes, 53 seconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
... And then gets stuck here forever.

No jar gets created.

**Comment by harrysethi** [comment]
Could you please confirm the configuration - especially the operating system.

**Comment by askmyhat** [comment]
I am using Ubuntu.
There is possible solution:
http://stackoverflow.com/questions/35138628/openie-4-2-cant-generate-standalone-jar-using-sbt

**Comment by KevinBassaDevelopment** [comment]
I fixed the issue by simply using intellij idea instead and importing the project as sbt project - here compiling & building the jar works without a problem!

**Comment by xuanchien** [comment]
I got this error when compiling the project

`Failed to execute goal on project cluewebextractor: Could not resolve dependencies for project edu.washington.cs.knowitall:cluewebextractor:jar:1.0-SNAPSHOT: Could not find artifact de.l3s.boilerpipe:boilerpipe:jar:1.2.0 in boilerpipe-m2-repo (https://boilerpipe.googlecode.com/svn/repo/) -> [Help 1]`

It seems like the repository https://boilerpipe.googlecode.com/svn/repo/ no longer exists. Any solution for this?

**Comment by bhadramani** [comment]
Use adequate java options 
-J-Xmx2700M or -J-Xmx10000M (depends on openie version)
 -Xmx4g -XX:+UseConcMarkSweepGC or  -Xmx6g / -Xmx8g / -Xmx10g  (depends on openie version)

It is advisable to use latest versions , as you may not be able to find some of the dependencies.
