### ISSUE TITLE
Compiled jar not compatible with scala 2.11.6

### ISSUE THREAD

**Issue by vikram-gupta** [knowitall/openie#26]
Hello friends,

I was able to create the standalone jar with the default settings but it did not work in a java project running on scala 2.11.6. I tried to create the jar by modifying the scala version but since the dependencies are not been compiled for scala 2.11.6, i could not proceed further.

Can someone suggest a good way to create scala 2.11.6 compatible jar?

Thanks

**Comment by harrysethi** [comment]
Please check https://github.com/allenai/openie-standalone

**Comment by vikram-gupta** [comment]
Thanks @harrysethi This really helps !
