### ISSUE TITLE
I created a copy of this repository that runs on 2.11

### ISSUE THREAD

**Issue by schmmd** [knowitall/openie#28]
I've received a couple of requests to get this on Scala 2.11.  I created a more standalone project at https://github.com/schmmd/openie-standalone.  It contains a number of the dependencies I originally authored, which made the migration easier.  This setup might also work for maintenance and the first commit runs on Scala 2.10.

Just an FYI!

**Comment by harrysethi** [comment]
As mentioned in the readMe, https://github.com/allenai/openie-standalone is the latest openIE standalone codebase, closing this.
