### ISSUE TITLE
Java  heap space exception

### ISSUE THREAD

**Issue by ROHITHKUMARN** [knowitall/openie#30]
Hi When i am trying to execute the simple application that uses openie to extract relations its throwing "java heap space exception" can some1 help fix this bug
<img width="1261" alt="screen shot 2017-07-15 at 6 47 34 pm" src="https://user-images.githubusercontent.com/24536547/28243423-26163c6a-698e-11e7-9d79-e2483dbd05d5.png">

**Comment by ROHITHKUMARN** [comment]
can some one help me fixing the issue

**Comment by humehta** [comment]
Can someone please help I am facing the same issue?

**Comment by bhadramani** [comment]
User adequate java options  while building  -J-Xmx2700M
Thereafter  -Xmx4g -XX:+UseConcMarkSweepGC 
If using later versions may need  -Xmx6g or  -Xmx10g
You should have RAM of size between 10GB - 16GB or more
